---
- hosts: localhost
  # `root` restricted from installing packages via `brew`
  # become: true
  vars:
    brew_zsh_path: "/usr/local/bin/zsh"

  roles:
    - common

  handlers:
    - name: Restart Finder
      command: killall Finder
