---

- name: Check if `kitty` terminal emulator is installed
  stat:
    path: /Applications/kitty.app
  register: kitty

- name: Install `kitty` if not present
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  args:
    creates: /Applications/kitty.app
  when: not kitty.stat.exists

# Ensure presence of correct `kitty` configuration file

- name: Define paths for `kitty` configuration file
  block:
    - set_fact:
        kitty_source: "/Users/{{ username }}/{{ workspace_dir }}/dotfiles-macos/main/files/home/kitty"
        kitty_destination: "/Users/{{ username }}/.config/kitty"

- name: Check existence of `kitty` config
  ansible.builtin.stat:
    path: "{{ kitty_destination }}"
  register: kittyconf

# - name: Display existence of kitty config
#   debug:
#     msg: 
#       - "kitty config does {{ 'exist' if kittyconf.stat.exists else 'not exist' }}"
#       - "kitty config is a {{ 'symlink' if kittyconf.stat.islnk else 'regular file' }}"

- name: Remove config if not a symlink
  file:
    path: "{{ kitty_destination }}"
    state: absent
  when: kittyconf.stat.exists and not kittyconf.stat.islnk

- name: Check if symlink target is correct
  set_fact:
    is_target_correct: "{{ kittyconf.stat.lnk_target == kitty_source }}"
  when: kittyconf.stat.exists and kittyconf.stat.islnk

# - name: Display result of symlink target check
#   debug: 
#     msg: "Symlink target is {{ 'correct' if is_target_correct else 'incorrect' }}"
#   when: kittyconf.stat.exists and kittyconf.stat.islnk

- name: Unlink symlink if target is incorrect
  file:
    path: "{{ kitty_destination }}"
    state: absent
  when: kittyconf.stat.exists and kittyconf.stat.islnk and not is_target_correct

- name: Create a symlink to correct file if needed
  file:
    src: "{{ kitty_source }}"
    dest: "{{ kitty_destination }}"
    state: link
  when: not kittyconf.stat.exists or not is_target_correct|default(false)
